version: "2"
services:
  plone:
    image: plone:5
    ports:
      - "8080"
    volumes:
      - ../../:/plone/instance/src/eea.virtualpages
    environment:
      ADDONS: "eea.virtualpages[test]"
      DEVELOP: "src/eea.virtualpages"
